services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: laravel_app
        ports:
            - "80:80"
            - "5173:5173"
        volumes:
            - ${PROJECT_PATH}:/var/www/html
            - /var/www/html/node_modules
        depends_on:
            - mysql
        working_dir: /var/www/html
        command: apache2-foreground
        user: "${UID:-1000}:${GID:-1000}"

    mysql:
        image: mysql:8.0.34
        container_name: laravel_mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
    mysql_data:
